services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: zoo_php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: zoo_web
    restart: unless-stopped
    ports:
      - "${NGINX_HOST}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: zoo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_HOST}:${DATABASE_PORT}"
    networks:
      - app_network
        
  node:
    image: node:20.4.0
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev-server && tail -f /dev/null"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge